name: Create PDF File

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp md-styles.css output/md-styles.css
          cp resume-${{ inputs.language }}.md output/resume-${{ inputs.language }}.md
      # Downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
          sudo apt install ./pandoc-2.14.2-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6-1.bionic_amd64.deb
        
      - name: "Convert MD to HTML"
        run: pandoc resume-${{ inputs.language }}.md -f markdown -t html -c md-styles.css -s -o output/resume-${{ inputs.language }}.html
          
      - name: "Convert HTML to PDF "
        run: wkhtmltopdf --enable-local-file-access output/resume-${{ inputs.language }}.html output/resume-${{ inputs.language }}.pdf
          
      - uses: actions/upload-artifact@master
        with: # basically this will put resume.md, resume.html, resume.pdf and resume-stylesheet.css in a zip file. 
          name: Resume - ${{ inputs.language }}
          path: output
