# This is a basic workflow to help you get started with Actions

name: Create english resume.pdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Master" branch
  push:
    branches: [ "Master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # this checks out the repo in the ubuntu container
        
      - name: "Create pdf"
        uses: ./.github/workflows/create-pdf.yml
        with:
          language: "english"
          secrets: inherit
